# Generated by Django 5.2.2 on 2025-06-26 00:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_convert_barangay_to_fk'),
        ('routers', '0003_remove_router_routers_rou_mac_add_835f3e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this installation is active')),
                ('installation_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the installation was completed')),
                ('installation_notes', models.TextField(blank=True, help_text='Additional notes about the installation')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', help_text='Current status of the installation', max_length=20)),
                ('customer', models.OneToOneField(help_text='Customer this installation belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='installation', to='customers.customer')),
                ('installation_technician', models.ForeignKey(help_text='Technician who performed the installation', on_delete=django.db.models.deletion.PROTECT, related_name='installations_performed', to=settings.AUTH_USER_MODEL)),
                ('router', models.ForeignKey(blank=True, help_text='Router assigned to this installation', null=True, on_delete=django.db.models.deletion.PROTECT, to='routers.router')),
            ],
            options={
                'verbose_name': 'Customer Installation',
                'verbose_name_plural': 'Customer Installations',
                'ordering': ['-installation_date'],
            },
        ),
    ]
