# Generated by Django 5.2.2 on 2025-06-30 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate (e.g., 8.4542363)', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate (e.g., 124.6318977)', max_digits=11, null=True)),
                ('location_accuracy', models.CharField(blank=True, choices=[('exact', 'Exact GPS'), ('approximate', 'Approximate'), ('address', 'From Address'), ('manual', 'Manual Entry')], default='manual', help_text='How the location was determined', max_length=50)),
                ('location_notes', models.CharField(blank=True, help_text='Additional notes about the location (landmark, building, etc.)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this installation is active')),
                ('nap_port', models.IntegerField(blank=True, help_text='Port number on the NAP (1-N based on NAP capacity)', null=True)),
                ('installation_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the installation was completed')),
                ('installation_notes', models.TextField(blank=True, help_text='Additional notes about the installation')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', help_text='Current status of the installation', max_length=20)),
            ],
            options={
                'verbose_name': 'Customer Installation',
                'verbose_name_plural': 'Customer Installations',
                'ordering': ['-installation_date'],
                'permissions': [('view_installation_list', 'Can view installation list'), ('view_installation_detail', 'Can view installation details'), ('create_installation', 'Can create new installation'), ('change_installation_status', 'Can change installation status'), ('assign_technician', 'Can assign technician to installation'), ('view_installation_technical_details', 'Can view technical details'), ('manage_nap_assignments', 'Can manage NAP port assignments'), ('export_installation_data', 'Can export installation data')],
            },
        ),
    ]
