# Generated by Django 5.2.2 on 2025-06-30 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_installations', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinstallation',
            name='customer',
            field=models.OneToOneField(help_text='Customer this installation belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='installation', to='customers.customer'),
        ),
    ]
