# Generated by Django 5.2.2 on 2025-06-28 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_installations', '0002_add_geolocation_fields'),
        ('lcp', '0004_add_coverage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinstallation',
            name='nap',
            field=models.ForeignKey(blank=True, help_text='NAP (Network Access Point) where customer is connected', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_installations', to='lcp.nap'),
        ),
        migrations.AddField(
            model_name='customerinstallation',
            name='nap_port',
            field=models.IntegerField(blank=True, help_text='Port number on the NAP (1-N based on NAP capacity)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customerinstallation',
            unique_together={('nap', 'nap_port')},
        ),
    ]
