# Generated by Django 5.2.2 on 2025-06-30 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_installations', '0002_initial'),
        ('lcp', '0002_initial'),
        ('routers', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinstallation',
            name='installation_technician',
            field=models.ForeignKey(help_text='Technician who performed the installation', on_delete=django.db.models.deletion.PROTECT, related_name='installations_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerinstallation',
            name='nap',
            field=models.ForeignKey(blank=True, help_text='NAP (Network Access Point) where customer is connected', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_installations', to='lcp.nap'),
        ),
        migrations.AddField(
            model_name='customerinstallation',
            name='router',
            field=models.ForeignKey(blank=True, help_text='Router assigned to this installation', null=True, on_delete=django.db.models.deletion.PROTECT, to='routers.router'),
        ),
        migrations.AddField(
            model_name='customerinstallation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='customerinstallation',
            unique_together={('nap', 'nap_port')},
        ),
    ]
