# Generated by Django 5.2.2 on 2025-06-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_installations', '0003_add_nap_port_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinstallation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', help_text='Current status of the installation', max_length=20),
        ),
    ]
