# Generated by Django 5.2.2 on 2025-06-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_installations', '0004_alter_customerinstallation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinstallation',
            options={'ordering': ['-installation_date'], 'permissions': [('view_installation_list', 'Can view installation list'), ('view_installation_detail', 'Can view installation details'), ('create_installation', 'Can create new installation'), ('change_installation_status', 'Can change installation status'), ('assign_technician', 'Can assign technician to installation'), ('view_installation_technical_details', 'Can view technical details'), ('manage_nap_assignments', 'Can manage NAP port assignments'), ('export_installation_data', 'Can export installation data')], 'verbose_name': 'Customer Installation', 'verbose_name_plural': 'Customer Installations'},
        ),
    ]
