# Generated by Django 5.2.2 on 2025-06-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the barangay', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Optional barangay code for reporting', max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional notes or description about the barangay')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this barangay is currently active')),
            ],
            options={
                'verbose_name': 'Barangay',
                'verbose_name_plural': 'Barangays',
                'ordering': ['name'],
                'permissions': [('view_barangay_list', 'Can view barangay list'), ('manage_barangay_status', 'Can activate/deactivate barangays'), ('view_barangay_statistics', 'Can view barangay statistics')],
            },
        ),
    ]
