# Generated by Django 5.2.2 on 2025-06-30 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='barangay',
            index=models.Index(fields=['tenant', 'name'], name='barangays_b_tenant__ede80d_idx'),
        ),
        migrations.AddIndex(
            model_name='barangay',
            index=models.Index(fields=['is_active'], name='barangays_b_is_acti_4f8ff0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='barangay',
            unique_together={('tenant', 'code'), ('tenant', 'name')},
        ),
    ]
