# Generated by Django manual creation

from django.db import migrations


def populate_barangays(apps, schema_editor):
    """Populate initial barangays data"""
    Barangay = apps.get_model("barangays", "Barangay")
    
    # List of all barangays in Cagayan de Oro
    barangays_data = [
        # Urban Barangays (Poblacion)
        {"name": "Barangay 1", "code": "1"},
        {"name": "Barangay 2", "code": "2"},
        {"name": "Barangay 3", "code": "3"},
        {"name": "Barangay 4", "code": "4"},
        {"name": "Barangay 5", "code": "5"},
        {"name": "Barangay 6", "code": "6"},
        {"name": "Barangay 7", "code": "7"},
        {"name": "Barangay 8", "code": "8"},
        {"name": "Barangay 9", "code": "9"},
        {"name": "Barangay 10", "code": "10"},
        {"name": "Barangay 11", "code": "11"},
        {"name": "Barangay 12", "code": "12"},
        {"name": "Barangay 13", "code": "13"},
        {"name": "Barangay 14", "code": "14"},
        {"name": "Barangay 15", "code": "15"},
        {"name": "Barangay 16", "code": "16"},
        {"name": "Barangay 17", "code": "17"},
        {"name": "Barangay 18", "code": "18"},
        {"name": "Barangay 19", "code": "19"},
        {"name": "Barangay 20", "code": "20"},
    ]
    
    for data in barangays_data:
        Barangay.objects.get_or_create(
            name=data["name"],
            defaults={"code": data["code"], "is_active": True}
        )

    # Add more barangays
    barangays_data.extend([
        {"name": "Barangay 21", "code": "21"},
        {"name": "Barangay 22", "code": "22"},
        {"name": "Barangay 23", "code": "23"},
        {"name": "Barangay 24", "code": "24"},
        {"name": "Barangay 25", "code": "25"},
        {"name": "Barangay 26", "code": "26"},
        {"name": "Barangay 27", "code": "27"},
        {"name": "Barangay 28", "code": "28"},
        {"name": "Barangay 29", "code": "29"},
        {"name": "Barangay 30", "code": "30"},
        {"name": "Barangay 31", "code": "31"},
        {"name": "Barangay 32", "code": "32"},
        {"name": "Barangay 33", "code": "33"},
        {"name": "Barangay 34", "code": "34"},
        {"name": "Barangay 35", "code": "35"},
        {"name": "Barangay 36", "code": "36"},
        {"name": "Barangay 37", "code": "37"},
        {"name": "Barangay 38", "code": "38"},
        {"name": "Barangay 39", "code": "39"},
        {"name": "Barangay 40", "code": "40"},
        # Major Barangays
        {"name": "Agusan", "code": "AGUS"},
        {"name": "Balulang", "code": "BALU"},
        {"name": "Bayabas", "code": "BAYA"},
        {"name": "Bonbon", "code": "BONB"},
        {"name": "Bugo", "code": "BUGO"},
        {"name": "Bulua", "code": "BULU"},
        {"name": "Camaman-an", "code": "CAMA"},
    ])

    barangays_data.extend([
        {"name": "Canitoan", "code": "CANI"},
        {"name": "Carmen", "code": "CARM"},
        {"name": "Consolacion", "code": "CONS"},
        {"name": "Cugman", "code": "CUGM"},
        {"name": "Gusa", "code": "GUSA"},
        {"name": "Iponan", "code": "IPON"},
        {"name": "Kauswagan", "code": "KAUS"},
        {"name": "Lapasan", "code": "LAPA"},
        {"name": "Lumbia", "code": "LUMB"},
        {"name": "Macabalan", "code": "MACA"},
        {"name": "Macasandig", "code": "MACS"},
        {"name": "Nazareth", "code": "NAZA"},
        {"name": "Patag", "code": "PATA"},
        {"name": "Puerto", "code": "PUER"},
        {"name": "Puntod", "code": "PUNT"},
        {"name": "Tablon", "code": "TABL"},
        {"name": "Tagoloan", "code": "TAGO"},
        {"name": "Taglimao", "code": "TAGL"},
        {"name": "Tignapoloan", "code": "TIGN"},
        # Other Barangays
        {"name": "Balubal", "code": "BLBL"},
        {"name": "Bayanga", "code": "BYNG"},
        {"name": "Besigan", "code": "BESG"},
        {"name": "Baikingon", "code": "BAIK"},
        {"name": "Dansolihon", "code": "DANS"},
        {"name": "F.S. Catanico", "code": "FSCA"},
        {"name": "Indahag", "code": "INDA"},
        {"name": "Mambuaya", "code": "MAMB"},
        {"name": "Pagalungan", "code": "PAGA"},
    ])

    barangays_data.extend([
        {"name": "Pagatpat", "code": "PGPT"},
        {"name": "Pigsag-an", "code": "PIGS"},
        {"name": "San Simon", "code": "SANS"},
        {"name": "Tuburan", "code": "TUBU"},
        {"name": "Tumpagon", "code": "TUMP"},
    ])
    
    for data in barangays_data:
        Barangay.objects.get_or_create(
            name=data["name"],
            defaults={"code": data["code"], "is_active": True}
        )


def reverse_populate_barangays(apps, schema_editor):
    """Remove populated barangays"""
    Barangay = apps.get_model("barangays", "Barangay")
    Barangay.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("barangays", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_barangays, reverse_populate_barangays),
    ]
