# Generated by Django manual creation

from django.db import migrations


def populate_barangays(apps, schema_editor):
    """Populate initial barangays data"""
    Barangay = apps.get_model("barangays", "Barangay")
    
    barangays_data = [
        {"name": "Macabal", "code": "MACA"},
        {"name": "Nazareth", "code": "NAZA"},
        {"name": "Kauswagan", "code": "KAUW"},
        {"name": "Lapasan", "code": "LAPS"},
        {"name": "Macasandig", "code": "MACS"},
        {"name": "Camaman-an", "code": "CAMM"},
    ]
    
    for data in barangays_data:
        Barangay.objects.get_or_create(
            name=data["name"],
            defaults={"code": data["code"], "is_active": True}
        )


def reverse_populate_barangays(apps, schema_editor):
    """Remove populated barangays"""
    Barangay = apps.get_model("barangays", "Barangay")
    Barangay.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("barangays", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_barangays, reverse_populate_barangays),
    ]
