# Generated by Django 5.2.2 on 2025-06-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangay',
            options={'ordering': ['name'], 'permissions': [('view_barangay_list', 'Can view barangay list'), ('manage_barangay_status', 'Can activate/deactivate barangays'), ('view_barangay_statistics', 'Can view barangay statistics')], 'verbose_name': 'Barangay', 'verbose_name_plural': 'Barangays'},
        ),
    ]
