# Generated by Django 5.2.2 on 2025-06-30 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0003_alter_barangay_options'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='barangay',
            name='barangays_b_name_7560ad_idx',
        ),
        migrations.AddField(
            model_name='barangay',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barangay',
            name='code',
            field=models.CharField(blank=True, help_text='Optional barangay code for reporting', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='name',
            field=models.CharField(help_text='Name of the barangay', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='barangay',
            unique_together={('tenant', 'code'), ('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='barangay',
            index=models.Index(fields=['tenant', 'name'], name='barangays_b_tenant__ede80d_idx'),
        ),
    ]
