# Generated by Django 5.2.2 on 2025-06-30 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate (e.g., 8.4542363)', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate (e.g., 124.6318977)', max_digits=11, null=True)),
                ('location_accuracy', models.CharField(blank=True, choices=[('exact', 'Exact GPS'), ('approximate', 'Approximate'), ('address', 'From Address'), ('manual', 'Manual Entry')], default='manual', help_text='How the location was determined', max_length=50)),
                ('location_notes', models.CharField(blank=True, help_text='Additional notes about the location (landmark, building, etc.)', max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_primary', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the customer')),
                ('barangay', models.ForeignKey(help_text="Customer's barangay", on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='barangays.barangay')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_customer_list', 'Can view customer list'), ('view_customer_detail', 'Can view customer details'), ('view_customer_sensitive_info', 'Can view sensitive customer information'), ('create_customer', 'Can create new customer'), ('change_customer_basic', 'Can edit customer basic information'), ('change_customer_status', 'Can change customer status'), ('change_customer_address', 'Can edit customer address'), ('remove_customer', 'Can remove customer'), ('bulk_delete_customers', 'Can bulk delete customers'), ('export_customers', 'Can export customer data'), ('import_customers', 'Can import customer data'), ('merge_duplicate_customers', 'Can merge duplicate customer records'), ('view_customer_coordinates', 'Can view customer GPS coordinates')],
            },
        ),
    ]
