# Generated by Django 5.2.2 on 2025-06-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0001_initial'),
        ('customers', '0002_remove_customer_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_email_4fdeb3_idx',
            old_name='customers_c_email_7f9e94_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_status_ce44cf_idx',
            old_name='customers_c_status_1cd0cf_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_last_na_27dbcc_idx',
            old_name='customers_c_last_na_f91b1d_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='barangay',
            field=models.ForeignKey(help_text="Customer's barangay", on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='barangays.barangay'),
        ),
    ]
