# Generated by Django 5.2.2 on 2025-06-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_convert_barangay_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='installation_notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='installation_technician',
        ),
    ]
