# Generated by Django 5.2.2 on 2025-06-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_add_geolocation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'permissions': [('view_customer_list', 'Can view customer list'), ('view_customer_detail', 'Can view customer details'), ('view_customer_sensitive_info', 'Can view sensitive customer information'), ('create_customer', 'Can create new customer'), ('change_customer_basic', 'Can edit customer basic information'), ('change_customer_status', 'Can change customer status'), ('change_customer_address', 'Can edit customer address'), ('remove_customer', 'Can remove customer'), ('bulk_delete_customers', 'Can bulk delete customers'), ('export_customers', 'Can export customer data'), ('import_customers', 'Can import customer data'), ('merge_duplicate_customers', 'Can merge duplicate customer records'), ('view_customer_coordinates', 'Can view customer GPS coordinates')]},
        ),
    ]
