services:
  db:
    image: postgres
    # persist data beyond lifetime of container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=isp_billing_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      retries: 10
  redis:
    image: redis
    # persistent storage
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: bash -c 'exec 6<>/dev/tcp/redis/6379'
      interval: 2s
      retries: 10
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        MY_UID: ${MY_UID:-1000}
        MY_GID: ${MY_GID:-1000}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: '1'
      PYTHONDONTWRITEBYTECODE: '1'
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
      args:
        MY_UID: ${MY_UID:-1000}
        MY_GID: ${MY_GID:-1000}
    command: npm run dev -- --host
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - "5173:5173"
    restart: unless-stopped
  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        MY_UID: ${MY_UID:-1000}
        MY_GID: ${MY_GID:-1000}
    command: celery -A isp_billing_system worker -l INFO --beat --pool=solo
    volumes:
      - .:/code
    environment:
      PYTHONUNBUFFERED: '1'
      PYTHONDONTWRITEBYTECODE: '1'
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
