FROM node:22-bookworm

# use latest npm
RUN npm install -g npm@11.3

RUN mkdir /code
# Change ownership of the workdir to the node user
RUN chown node:node /code
WORKDIR /code

# Switch to the node user before copying files and running npm install
USER node

COPY package.json package.json
# npm install will now run as the node user
RUN npm install

COPY . /code/
