cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _pegasus_version: 2025.6.1
  author_name: Alde
  bundler: vite
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: kamal
  description: Billing System
  docker_setup: default
  domain_name: localhost:8000
  email: aldesabido@gmail.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  github_username: ysystech
  include_static_files: n
  marketing_email_platform: none
  plugins: []
  post_process: y
  project_name: ISP Billing System
  project_slug: isp_billing_system
  python_package_manager: pip-tools
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: n
  use_ai_rules_claude: y
  use_ai_rules_cursor: y
  use_ai_rules_junie: n
  use_api_auth: y
  use_api_keys: n
  use_async: n
  use_celery: y
  use_cloud_media_storage: y
  use_dark_mode: n
  use_debug_toolbar: n
  use_docker: y
  use_ecommerce_example: n
  use_examples: n
  use_flowbite: y
  use_health_checks: n
  use_impersonation: n
  use_sentry: n
  use_shadcn: n
  use_subscriptions: n
  use_teams: n
  use_teams_example: n
  use_translations: n
  use_wagtail: n
