# Generated by Django 2.1.7 on 2019-03-21 12:18
from django.conf import settings
from django.db import migrations


def create_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site = Site.objects.get_or_create(
        id=settings.SITE_ID
    )[0]
    # strip leading http:// from site url since django sites framework doesn't expect it
    site.domain = settings.PROJECT_METADATA['URL'].replace('http://', '').replace('https://', '')
    # site names have a max of 50 chars
    site.name = settings.PROJECT_METADATA['NAME'][:50]
    site.save()
    # Set the sequence to the next available value
    if schema_editor.connection.vendor == 'postgresql':
        # this is the output of `./manage.py sqlsequencereset sites` with the surrounding blocks removed.
        RESET_SQL = """
        SELECT setval(pg_get_serial_sequence('"django_site"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_site";
        """
        schema_editor.execute(RESET_SQL)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_site),
    ]
