# Generated by Django 5.2.2 on 2025-06-30 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the subscription plan', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what the plan includes')),
                ('speed', models.IntegerField(help_text='Internet speed in Mbps', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PHP', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('day_count', models.IntegerField(default=30, help_text='Number of days this plan is valid for', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently available for new subscriptions')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price', 'name'],
                'permissions': [('view_subscriptionplan_list', 'Can view subscription plan list'), ('change_subscriptionplan_pricing', 'Can change plan pricing'), ('activate_deactivate_plans', 'Can activate/deactivate plans'), ('create_promotional_plans', 'Can create promotional plans')],
            },
        ),
    ]
