# Generated by Django 5.2.2 on 2025-06-26 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='day_count',
            field=models.IntegerField(default=30, help_text='Number of days this plan is valid for', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in PHP', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
