# Generated by Django 5.2.2 on 2025-06-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_day_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price', 'name'], 'permissions': [('view_subscriptionplan_list', 'Can view subscription plan list'), ('change_subscriptionplan_pricing', 'Can change plan pricing'), ('activate_deactivate_plans', 'Can activate/deactivate plans'), ('create_promotional_plans', 'Can create promotional plans')], 'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
    ]
