# Generated by Django 5.2.2 on 2025-06-30 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptionplan_options'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Name of the subscription plan', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('tenant', 'name')},
        ),
    ]
