# Generated by Django 5.2.2 on 2025-06-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_network_map', 'Can view network map'), ('view_network_hierarchy', 'Can view network hierarchy'), ('export_network_data', 'Can export network data'), ('view_coverage_analysis', 'Can view coverage analysis')],
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
