# Generated by Django 5.2.2 on 2025-06-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CASHIER', 'Cashier'), ('TECHNICIAN', 'Installer/Technician')], default='CASHIER', help_text='Type of user in the system', max_length=20),
        ),
    ]
