# Generated by Django 5.2.2 on 2025-06-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_convert_admins_to_cashiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CASHIER', 'Cashier'), ('TECHNICIAN', 'Installer/Technician')], default='CASHIER', help_text='Type of user in the system', max_length=20),
        ),
    ]
