# Generated by Django 5.2.2 on 2025-06-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0006_remove_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tenant_owner',
            field=models.BooleanField(default=False, help_text='Tenant owners bypass all permissions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant'),
        ),
    ]
