# Generated by Django 5.2.2 on 2025-06-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(editable=False, help_text='Auto-generated ticket number', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Brief description of the issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('category', models.CharField(choices=[('no_connection', 'No Internet Connection'), ('slow_connection', 'Slow Internet Speed'), ('intermittent', 'Intermittent Connection'), ('router_issue', 'Router/Equipment Problem'), ('billing', 'Billing Inquiry'), ('relocation', 'Relocation Request'), ('upgrade', 'Plan Upgrade Request'), ('downgrade', 'Plan Downgrade Request'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('phone', 'Phone Call'), ('messenger', 'Facebook Messenger'), ('walk_in', 'Walk-in'), ('email', 'Email'), ('sms', 'SMS'), ('other', 'Other')], default='phone', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the ticket was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the issue was resolved')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_ticket_list', 'Can view ticket list'), ('view_ticket_detail', 'Can view ticket details'), ('create_ticket', 'Can create new ticket'), ('assign_ticket', 'Can assign ticket to technician'), ('change_ticket_status', 'Can change ticket status'), ('change_ticket_priority', 'Can change ticket priority'), ('add_ticket_comment', 'Can add comments to tickets'), ('view_all_tickets', 'Can view all tickets (not just assigned)'), ('export_ticket_data', 'Can export ticket data'), ('remove_ticket', 'Can remove ticket')],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
            ],
            options={
                'ordering': ['created_at'],
                'permissions': [('view_ticket_comments', 'Can view ticket comments'), ('delete_any_comment', 'Can delete any comment')],
            },
        ),
    ]
