# Generated by Django 5.2.2 on 2025-06-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'permissions': [('view_ticket_list', 'Can view ticket list'), ('view_ticket_detail', 'Can view ticket details'), ('create_ticket', 'Can create new ticket'), ('assign_ticket', 'Can assign ticket to technician'), ('change_ticket_status', 'Can change ticket status'), ('change_ticket_priority', 'Can change ticket priority'), ('add_ticket_comment', 'Can add comments to tickets'), ('view_all_tickets', 'Can view all tickets (not just assigned)'), ('export_ticket_data', 'Can export ticket data'), ('remove_ticket', 'Can remove ticket')]},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created_at'], 'permissions': [('view_ticket_comments', 'Can view ticket comments'), ('delete_any_comment', 'Can delete any comment')]},
        ),
    ]
