service: isp_billing_system

image: <namespace>/isp_billing_system

env:
  # This is the minimal set of environment variables needed to run the app
  # in production. You can add more here and in the .kamal/secrets file as needed.
  clear:
    DJANGO_SETTINGS_MODULE: isp_billing_system.settings_production
    ALLOWED_HOSTS: "localhost:8000"
    USE_S3_MEDIA: "True"
    AWS_STORAGE_BUCKET_NAME: "isp-billing-system-media"
    DEFAULT_FROM_EMAIL: "aldesabido@gmail.com"
    SERVER_EMAIL: "noreply@localhost:8000"
    # uncomment and set to your preferred production email backend
    # EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
    CORS_ALLOWED_ORIGINS: "https://app.localhost:8000,https://localhost:8000"
    FRONTEND_ADDRESS: "https://localhost:8000"
    CSRF_COOKIE_DOMAIN: ".localhost:8000"
    SESSION_COOKIE_DOMAIN: ".localhost:8000"
  secret:
    - POSTGRES_PASSWORD
    - SECRET_KEY
    - DATABASE_URL
    - REDIS_URL
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - TURNSTILE_KEY
    - TURNSTILE_SECRET

# https://kamal-deploy.org/docs/configuration#using-different-roles-for-servers
servers:
  web:
    hosts:
      - <IP-ADDRESS>
    options:
      expose: "8000"
  celery:
    hosts:
      - <IP-ADDRESS>
    cmd: celery -A isp_billing_system worker -l INFO --pool gevent --concurrency 20

  celerybeat:
    hosts:
      - <IP-ADDRESS>
    cmd: celery -A isp_billing_system beat -l INFO


# To use a non-root user see https://kamal-deploy.org/docs/configuration/ssh/#the-ssh-user
# ssh:
#   user: kamal

# See https://kamal-deploy.org/docs/configuration/builders/ for config options
builder:
  arch: amd64
  dockerfile: "Dockerfile.web"

# See https://kamal-deploy.org/docs/configuration/docker-registry/ for config options
registry:
  username: <DOCKER REGISTRY USERNAME>
  password:
    - KAMAL_REGISTRY_PASSWORD

accessories:
  # docker hostname will be "isp_billing_system-postgres"
  postgres:
    image: postgres
    host: <IP-ADDRESS>
    directories:
      - data:/var/lib/postgresql/data
    env:
      clear:
        POSTGRES_USER: isp_billing_system
        POSTGRES_DB: isp_billing_system
      secret:
        - POSTGRES_PASSWORD
  ## docker hostname will be "isp_billing_system-redis"
  redis:
    image: redis
    host: <IP-ADDRESS>

# See https://kamal-deploy.org/docs/configuration/proxy/ for config options
proxy:
  ssl: true
  host: localhost:8000
  app_port: 8000
