# Generated by Django 5.2.2 on 2025-06-26 00:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_installations', '0001_initial'),
        ('subscriptions', '0002_subscriptionplan_day_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this subscription period starts')),
                ('end_date', models.DateTimeField(help_text='When this subscription period ends (calculated from start_date + plan.day_count)')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Actual amount paid by customer', max_digits=10)),
                ('is_paid', models.BooleanField(default=True, help_text='Whether payment has been received (always True for prepaid)')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When payment was received')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('GCASH', 'GCash'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', help_text='Method of payment', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Reference number for GCash/Bank transfers', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this subscription/payment')),
                ('collected_by', models.ForeignKey(help_text='Cashier who processed this payment', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_collected', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(help_text='Customer installation this subscription belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customer_installations.customerinstallation')),
                ('plan', models.ForeignKey(help_text='Subscription plan selected', on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Customer Subscription',
                'verbose_name_plural': 'Customer Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
    ]
