# Generated by Django 5.2.2 on 2025-06-28 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_installations', '0004_alter_customerinstallation_status'),
        ('subscriptions', '0002_subscriptionplan_day_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_type', models.CharField(choices=[('one_month', '1 Month'), ('fifteen_days', '15 Days'), ('custom', 'Custom Amount')], help_text='Type of subscription payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid by customer', max_digits=10)),
                ('start_date', models.DateTimeField(help_text='When the subscription starts')),
                ('end_date', models.DateTimeField(help_text='When the subscription ends')),
                ('days_added', models.DecimalField(decimal_places=2, help_text='Number of days added (can be fractional)', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_created', to=settings.AUTH_USER_MODEL)),
                ('customer_installation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customer_installations.customerinstallation')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['customer_installation', 'status'], name='customer_su_custome_df328b_idx'), models.Index(fields=['start_date', 'end_date'], name='customer_su_start_d_6a3866_idx')],
            },
        ),
    ]
