# Generated by Django 5.2.2 on 2025-06-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_type', models.CharField(choices=[('one_month', '1 Month'), ('fifteen_days', '15 Days'), ('custom', 'Custom Amount')], help_text='Type of subscription payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid by customer', max_digits=10)),
                ('start_date', models.DateTimeField(help_text='When the subscription starts')),
                ('end_date', models.DateTimeField(help_text='When the subscription ends')),
                ('days_added', models.DecimalField(decimal_places=2, help_text='Number of days added (can be fractional)', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'permissions': [('view_subscription_list', 'Can view subscription list'), ('view_subscription_detail', 'Can view subscription details'), ('create_subscription', 'Can create new subscription'), ('process_payment', 'Can process subscription payment'), ('generate_receipt', 'Can generate payment receipt'), ('cancel_subscription', 'Can cancel subscription'), ('view_payment_history', 'Can view payment history'), ('export_subscription_data', 'Can export subscription data'), ('view_financial_summary', 'Can view financial summary'), ('process_refund', 'Can process subscription refund')],
            },
        ),
    ]
