# Generated by Django 5.2.2 on 2025-06-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersubscription',
            options={'ordering': ['-start_date'], 'permissions': [('view_subscription_list', 'Can view subscription list'), ('view_subscription_detail', 'Can view subscription details'), ('create_subscription', 'Can create new subscription'), ('process_payment', 'Can process subscription payment'), ('generate_receipt', 'Can generate payment receipt'), ('cancel_subscription', 'Can cancel subscription'), ('view_payment_history', 'Can view payment history'), ('export_subscription_data', 'Can export subscription data'), ('view_financial_summary', 'Can view financial summary'), ('process_refund', 'Can process subscription refund')]},
        ),
    ]
