# Generated by Django 5.2.2 on 2025-06-30 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_installations', '0003_initial'),
        ('customer_subscriptions', '0001_initial'),
        ('subscriptions', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='customer_installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customer_installations.customerinstallation'),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['customer_installation', 'status'], name='customer_su_custome_df328b_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['start_date', 'end_date'], name='customer_su_start_d_6a3866_idx'),
        ),
    ]
