# Generated by Django 5.2.2 on 2025-06-30 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(help_text='Router manufacturer (e.g., TP-Link, Mikrotik, Ubiquiti)', max_length=50)),
                ('model', models.CharField(blank=True, help_text='Router model number', max_length=100)),
                ('serial_number', models.CharField(help_text='Unique serial number from manufacturer', max_length=100)),
                ('mac_address', models.CharField(help_text='MAC address of the router (e.g., 00:11:22:33:44:55)', max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., 00:11:22:33:44:55 or 00-11-22-33-44-55)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')])),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this router')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_router_list', 'Can view router list'), ('view_router_detail', 'Can view router details'), ('manage_router_inventory', 'Can manage router inventory'), ('export_router_data', 'Can export router data'), ('bulk_import_routers', 'Can bulk import routers'), ('view_router_mac_address', 'Can view router MAC addresses')],
            },
        ),
    ]
