# Generated by Django 5.2.2 on 2025-06-25 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_convert_barangay_to_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(help_text='Router manufacturer (e.g., TP-Link, Mikrotik, Ubiquiti)', max_length=50)),
                ('model', models.CharField(help_text='Router model number', max_length=100)),
                ('serial_number', models.CharField(help_text='Unique serial number from manufacturer', max_length=100, unique=True)),
                ('mac_address', models.CharField(help_text='MAC address in format XX:XX:XX:XX:XX:XX', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., AA:BB:CC:DD:EE:FF)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')])),
                ('purchase_date', models.DateField(blank=True, help_text='Date when router was purchased', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price in PHP', max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, help_text='Where the router was purchased from', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('deployed', 'Deployed'), ('maintenance', 'Under Maintenance'), ('defective', 'Defective'), ('retired', 'Retired')], default='available', max_length=20)),
                ('deployment_date', models.DateField(blank=True, help_text='Date when router was deployed to current customer', null=True)),
                ('firmware_version', models.CharField(blank=True, help_text='Current firmware version', max_length=50)),
                ('wifi_password', models.CharField(blank=True, help_text='Default WiFi password set on router', max_length=100)),
                ('admin_password', models.CharField(blank=True, help_text='Router admin password (keep secure!)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this router')),
                ('current_customer', models.ForeignKey(blank=True, help_text='Customer currently using this router', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routers', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['serial_number'], name='routers_rou_serial__00224e_idx'), models.Index(fields=['mac_address'], name='routers_rou_mac_add_835f3e_idx'), models.Index(fields=['status'], name='routers_rou_status_bfb872_idx'), models.Index(fields=['current_customer'], name='routers_rou_current_e6d1b5_idx')],
            },
        ),
    ]
