# Generated by Django 5.2.2 on 2025-06-25 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='router',
            name='routers_rou_status_bfb872_idx',
        ),
        migrations.RemoveIndex(
            model_name='router',
            name='routers_rou_current_e6d1b5_idx',
        ),
        migrations.RemoveField(
            model_name='router',
            name='admin_password',
        ),
        migrations.RemoveField(
            model_name='router',
            name='current_customer',
        ),
        migrations.RemoveField(
            model_name='router',
            name='deployment_date',
        ),
        migrations.RemoveField(
            model_name='router',
            name='firmware_version',
        ),
        migrations.RemoveField(
            model_name='router',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='router',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='router',
            name='status',
        ),
        migrations.RemoveField(
            model_name='router',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='router',
            name='wifi_password',
        ),
        migrations.AlterField(
            model_name='router',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC address in format XX:XX:XX:XX:XX:XX', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., AA:BB:CC:DD:EE:FF)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
        migrations.AlterField(
            model_name='router',
            name='model',
            field=models.CharField(blank=True, help_text='Router model number', max_length=100),
        ),
    ]
