# Generated by Django 5.2.2 on 2025-06-30 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['tenant', 'serial_number'], name='routers_rou_tenant__be41dd_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['tenant', 'mac_address'], name='routers_rou_tenant__b1dad9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='router',
            unique_together={('tenant', 'mac_address'), ('tenant', 'serial_number')},
        ),
    ]
