# Generated by Django 5.2.2 on 2025-06-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0002_remove_router_routers_rou_status_bfb872_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='router',
            name='routers_rou_mac_add_835f3e_idx',
        ),
        migrations.RemoveField(
            model_name='router',
            name='mac_address',
        ),
    ]
