# Generated by Django 5.2.2 on 2025-06-28 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_remove_router_routers_rou_mac_add_835f3e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC address of the router (e.g., 00:11:22:33:44:55)', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., 00:11:22:33:44:55 or 00-11-22-33-44-55)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
    ]
