# Generated by Django 5.2.2 on 2025-07-01 13:36

from django.db import migrations, models


def convert_all_to_mikrotik(apps, schema_editor):
    """Convert all existing routers to Mikrotik brand and restore original model values"""
    Router = apps.get_model('routers', 'Router')
    
    for router in Router.objects.all():
        # Set brand to Mikrotik
        router.brand = 'Mikrotik'
        
        # If the model was set to 'other' in the previous migration and we have the original in notes
        if router.model == 'other' and router.notes and 'Original model:' in router.notes:
            # Extract the original model from notes
            lines = router.notes.split('\n')
            for i, line in enumerate(lines):
                if line.startswith('Original model:'):
                    original_model = line.replace('Original model:', '').strip()
                    router.model = original_model
                    # Remove this line from notes
                    lines.pop(i)
                    router.notes = '\n'.join(lines).strip()
                    break
        
        router.save()


def reverse_migration(apps, schema_editor):
    """This migration is not reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_alter_router_model'),
    ]

    operations = [
        # First convert model field back to text field
        migrations.AlterField(
            model_name='router',
            name='model',
            field=models.CharField(blank=True, help_text='Router model (e.g., hAP ac2, Archer C6)', max_length=100),
        ),
        
        # Run data migration to set all brands to Mikrotik
        migrations.RunPython(convert_all_to_mikrotik, reverse_migration),
        
        # Then alter brand field to use choices
        migrations.AlterField(
            model_name='router',
            name='brand',
            field=models.CharField(choices=[('Mikrotik', 'Mikrotik'), ('TP-Link', 'TP-Link'), ('Ubiquiti', 'Ubiquiti'), ('Tenda', 'Tenda'), ('Huawei', 'Huawei'), ('Cisco', 'Cisco'), ('Netgear', 'Netgear'), ('Asus', 'Asus'), ('D-Link', 'D-Link'), ('Xiaomi', 'Xiaomi'), ('Other', 'Other')], default='Mikrotik', help_text='Router manufacturer', max_length=50),
        ),
    ]
