# Generated by Django 5.2.2 on 2025-06-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0004_add_mac_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='router',
            options={'ordering': ['-created_at'], 'permissions': [('view_router_list', 'Can view router list'), ('view_router_detail', 'Can view router details'), ('manage_router_inventory', 'Can manage router inventory'), ('export_router_data', 'Can export router data'), ('bulk_import_routers', 'Can bulk import routers'), ('view_router_mac_address', 'Can view router MAC addresses')]},
        ),
    ]
