# Generated by Django 5.2.2 on 2025-06-29 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0006_populate_mac_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='mac_address',
            field=models.CharField(help_text='MAC address of the router (e.g., 00:11:22:33:44:55)', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., 00:11:22:33:44:55 or 00-11-22-33-44-55)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
    ]
