# Generated by Django 5.2.2 on 2025-06-30 00:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0007_make_mac_address_required'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='router',
            name='routers_rou_serial__00224e_idx',
        ),
        migrations.AddField(
            model_name='router',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='router',
            name='mac_address',
            field=models.CharField(help_text='MAC address of the router (e.g., 00:11:22:33:44:55)', max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., 00:11:22:33:44:55 or 00-11-22-33-44-55)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
        migrations.AlterField(
            model_name='router',
            name='serial_number',
            field=models.CharField(help_text='Unique serial number from manufacturer', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='router',
            unique_together={('tenant', 'mac_address'), ('tenant', 'serial_number')},
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['tenant', 'serial_number'], name='routers_rou_tenant__be41dd_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['tenant', 'mac_address'], name='routers_rou_tenant__b1dad9_idx'),
        ),
    ]
