# Generated by Django 5.2.2 on 2025-06-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique identifier (e.g., LCP-001)', max_length=50, unique=True)),
                ('location', models.TextField(help_text='Physical address or description')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lcps', to='barangays.barangay')),
            ],
            options={
                'verbose_name': 'LCP',
                'verbose_name_plural': 'LCPs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Splitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Splitter identifier (e.g., SP-001)', max_length=50)),
                ('type', models.CharField(choices=[('1:4', '1:4 (4 ports)'), ('1:8', '1:8 (8 ports)'), ('1:16', '1:16 (16 ports)'), ('1:32', '1:32 (32 ports)'), ('1:64', '1:64 (64 ports)')], help_text='Splitter ratio', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Specific location within LCP or elsewhere', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('lcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitters', to='lcp.lcp')),
            ],
            options={
                'ordering': ['lcp', 'code'],
                'unique_together': {('lcp', 'code')},
            },
        ),
        migrations.CreateModel(
            name='NAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('splitter_port', models.IntegerField(help_text='Which output port on the splitter (1-N)')),
                ('code', models.CharField(help_text='NAP identifier (e.g., NAP-001)', max_length=50)),
                ('name', models.CharField(help_text='Descriptive name for the NAP', max_length=100)),
                ('location', models.TextField(help_text='Physical location of the NAP box')),
                ('port_capacity', models.IntegerField(default=8, help_text='Number of customer ports in this NAP')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('splitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naps', to='lcp.splitter')),
            ],
            options={
                'verbose_name': 'NAP',
                'verbose_name_plural': 'NAPs',
                'ordering': ['splitter__lcp', 'splitter', 'splitter_port'],
                'unique_together': {('splitter', 'splitter_port')},
            },
        ),
    ]
