# Generated by Django 5.2.2 on 2025-06-30 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lcp', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcp',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nap',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='splitter',
            name='lcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splitters', to='lcp.lcp'),
        ),
        migrations.AddField(
            model_name='splitter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='nap',
            name='splitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naps', to='lcp.splitter'),
        ),
        migrations.AlterUniqueTogether(
            name='lcp',
            unique_together={('tenant', 'code'), ('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='splitter',
            unique_together={('lcp', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='nap',
            unique_together={('splitter', 'code')},
        ),
    ]
