# Generated by Django 5.2.2 on 2025-06-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nap',
            unique_together={('splitter', 'code')},
        ),
    ]
