# Generated by Django 5.2.2 on 2025-06-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcp', '0002_remove_unique_splitter_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcp',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate (e.g., 8.4542363)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lcp',
            name='location_accuracy',
            field=models.CharField(blank=True, choices=[('exact', 'Exact GPS'), ('approximate', 'Approximate'), ('address', 'From Address'), ('manual', 'Manual Entry')], default='manual', help_text='How the location was determined', max_length=50),
        ),
        migrations.AddField(
            model_name='lcp',
            name='location_notes',
            field=models.CharField(blank=True, help_text='Additional notes about the location (landmark, building, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='lcp',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate (e.g., 124.6318977)', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='nap',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate (e.g., 8.4542363)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nap',
            name='location_accuracy',
            field=models.CharField(blank=True, choices=[('exact', 'Exact GPS'), ('approximate', 'Approximate'), ('address', 'From Address'), ('manual', 'Manual Entry')], default='manual', help_text='How the location was determined', max_length=50),
        ),
        migrations.AddField(
            model_name='nap',
            name='location_notes',
            field=models.CharField(blank=True, help_text='Additional notes about the location (landmark, building, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='nap',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate (e.g., 124.6318977)', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='splitter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate (e.g., 8.4542363)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='splitter',
            name='location_accuracy',
            field=models.CharField(blank=True, choices=[('exact', 'Exact GPS'), ('approximate', 'Approximate'), ('address', 'From Address'), ('manual', 'Manual Entry')], default='manual', help_text='How the location was determined', max_length=50),
        ),
        migrations.AddField(
            model_name='splitter',
            name='location_notes',
            field=models.CharField(blank=True, help_text='Additional notes about the location (landmark, building, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='splitter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate (e.g., 124.6318977)', max_digits=11, null=True),
        ),
    ]
