# Generated by Django 5.2.2 on 2025-06-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcp', '0003_add_geolocation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcp',
            name='coverage_radius_meters',
            field=models.IntegerField(default=1000, help_text='Approximate coverage area radius in meters'),
        ),
        migrations.AddField(
            model_name='nap',
            name='max_distance_meters',
            field=models.IntegerField(default=100, help_text='Maximum recommended customer distance in meters'),
        ),
    ]
