# Generated by Django 5.2.2 on 2025-06-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcp', '0004_add_coverage_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lcp',
            options={'ordering': ['code'], 'permissions': [('view_lcp_list', 'Can view LCP list'), ('view_lcp_detail', 'Can view LCP details'), ('manage_lcp_infrastructure', 'Can manage LCP infrastructure'), ('view_lcp_map', 'Can view LCP on map'), ('export_lcp_data', 'Can export LCP data')], 'verbose_name': 'LCP', 'verbose_name_plural': 'LCPs'},
        ),
        migrations.AlterModelOptions(
            name='nap',
            options={'ordering': ['splitter__lcp', 'splitter', 'splitter_port'], 'permissions': [('view_nap_list', 'Can view NAP list'), ('view_nap_detail', 'Can view NAP details'), ('manage_nap_ports', 'Can manage NAP ports'), ('view_nap_availability', 'Can view NAP port availability')], 'verbose_name': 'NAP', 'verbose_name_plural': 'NAPs'},
        ),
        migrations.AlterModelOptions(
            name='splitter',
            options={'ordering': ['lcp', 'code'], 'permissions': [('view_splitter_list', 'Can view splitter list'), ('view_splitter_detail', 'Can view splitter details'), ('manage_splitter_ports', 'Can manage splitter ports')]},
        ),
    ]
