# Generated by Django 5.2.2 on 2025-06-30 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcp', '0005_alter_lcp_options_alter_nap_options_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcp',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nap',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splitter',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lcp',
            name='code',
            field=models.CharField(help_text='Unique identifier (e.g., LCP-001)', max_length=50),
        ),
        migrations.AlterField(
            model_name='lcp',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='lcp',
            unique_together={('tenant', 'code'), ('tenant', 'name')},
        ),
    ]
