# Generated by Django 5.2.2 on 2025-06-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_daily_collection_report', 'Can view daily collection report'), ('view_subscription_expiry_report', 'Can view subscription expiry report'), ('export_operational_reports', 'Can export operational reports'), ('view_monthly_revenue_report', 'Can view monthly revenue report'), ('view_ticket_analysis_report', 'Can view ticket analysis report'), ('view_technician_performance_report', 'Can view technician performance report'), ('view_customer_acquisition_report', 'Can view customer acquisition report'), ('view_payment_behavior_report', 'Can view payment behavior report'), ('export_business_reports', 'Can export business intelligence reports'), ('view_area_performance_dashboard', 'Can view area performance dashboard'), ('view_financial_dashboard', 'Can view financial dashboard'), ('access_advanced_analytics', 'Can access advanced analytics'), ('schedule_reports', 'Can schedule automated reports'), ('customize_report_parameters', 'Can customize report parameters')],
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
