# Generated by Django 5.2.2 on 2025-06-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='session_key',
            field=models.CharField(blank=True, help_text='Django session key', max_length=40, null=True),
        ),
    ]
