# Generated by Django 5.1.4 on 2025-01-29

from django.db import migrations, models
import django.db.models.deletion


def get_default_tenant_id():
    """Get the ID of the first tenant to use as default."""
    from apps.tenants.models import Tenant
    tenant = Tenant.objects.first()
    if tenant:
        return tenant.id
    return 1  # Fallback, though this shouldn't happen


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('audit_logs', '0002_make_session_key_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='tenant',
            field=models.ForeignKey(
                default=get_default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(class)s_set',
                to='tenants.tenant'
            ),
            preserve_default=False,
        ),
    ]
